# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('visitor_name', models.CharField(blank=True, max_length=255, verbose_name='Visitor Name')),
                ('visitor_email', models.EmailField(blank=True, max_length=254, verbose_name='Visitor Email')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('assigned_to', models.UUIDField(blank=True, null=True, verbose_name='Assigned To')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating')),
            ],
            options={
                'db_table': 'live_chat_chatconversation',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('sender_type', models.CharField(default='visitor', max_length=10, verbose_name='Sender Type')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Sender Name')),
                ('message', models.TextField(verbose_name='Message')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live_chat.chatconversation')),
            ],
            options={
                'db_table': 'live_chat_chatmessage',
                'abstract': False,
            },
        ),
    ]
